### ISSUE TITLE
Allowed memory size of  bytes exhausted

### ISSUE THREAD

**Issue by shencw** [jonahgeorge/jaeger-client-php#105]
Allowed memory size of 419430400 bytes exhausted (tried to allocate 65536 bytes) in     jaeger-client-php/src/Jaeger/Thrift/Agent/Agent_emitBatch_args.php on line 51

**Comment by sergeyklay** [comment]
This largely depends on the amount of data and will never truly be universal, because there will always be such a case when there is more data than memory. We store about 1 terabyte of traces per day using jaeger-client-php and have never faced a lack of memory. I recommend looking at the your OpenTracing patterns, studying the used workflow and finding places for optimization yourself.
